### ISSUE TITLE
Left nav bar, right ToC and content should match Carbon left-right grid influencers

### ISSUE THREAD

**Issue by rampadc** [rampadc/antora-x-carbon#1]
Examples:

Left nav: 256px fix width
Right nav: 320px fix width 

https://carbondesignsystem.com/guidelines/2x-grid/overview/#grid-influencers
https://pages.github.ibm.com/cdai-design/cloud-pal/cloudpal-guidance/grid
https://pages.github.ibm.com/ibmcloud/pal/storybook/?path=/docs/layouts-worldlevellayout--example

**Comment by hs-07** [comment]
hello @rampadc , Can you telling something more about the bug?
I would like to help you to fix the issue.

**Comment by rampadc** [comment]
Thanks for offering to help @hs-07, at the moment, these issues are just for my tracking. I'm not seeking external help at this point.

**Comment by rampadc** [comment]
fixed in https://github.com/rampadc/antora-x-carbon/commit/d6afb1ad6dae96aca57c762cbdc9554c5a07a7a4
